import "./globals.css";
import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import { getServerSession } from "next-auth";

import SessionProvider from "@/providers/SessionProvider";
import { Toaster } from "@/shared/components/ui/toaster";
const font = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Team Chat Application",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <body className={font.className}>
        <SessionProvider session={session}>
          {children}
          <Toaster />
        </SessionProvider>
      </body>
    </html>
  );
}
